saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.product_list, name="product-list"),
    url(r"^(?P<pk>[0-9]+)/$", views.product_details, name="product-details"),
    url(
        r"^(?P<pk>[0-9]+)/publish/$",
        views.product_toggle_is_published,
        name="product-publish",
    ),
    url(
        r"^add/select-type/$", views.product_select_type, name="product-add-select-type"
    ),
    url(r"^add/(?P<type_pk>[0-9]+)/$", views.product_create, name="product-add"),
    url(r"^(?P<pk>[0-9]+)/update/$", views.product_edit, name="product-update"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.product_delete, name="product-delete"),
    url(r"^bulk-update/$", views.product_bulk_update, name="product-bulk-update"),
    url(r"^ajax/products/$", views.ajax_products_list, name="ajax-products"),
    url(r"^types/$", views.product_type_list, name="product-type-list"),
    url(r"^types/add/$", views.product_type_create, name="product-type-add"),
    url(
        r"^types/(?P<pk>[0-9]+)/update/$",
        views.product_type_edit,
        name="product-type-update",
    ),
    url(
        r"^types/(?P<pk>[0-9]+)/delete/$",
        views.product_type_delete,
        name="product-type-delete",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$",
        views.variant_details,
        name="variant-details",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/add/$",
        views.variant_create,
        name="variant-add",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/update/$",
        views.variant_edit,
        name="variant-update",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$",
        views.variant_delete,
        name="variant-delete",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/images/$",
        views.variant_images,
        name="variant-images",
    ),
    url(
        r"^ajax/variants/$",
        views.ajax_available_variants_list,
        name="ajax-available-variants",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/$",
        views.product_images,
        name="product-image-list",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/add/$",
        views.product_image_create,
        name="product-image-add",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$",
        views.product_image_edit,
        name="product-image-update",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$",
        views.product_image_delete,
        name="product-image-delete",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/reorder/$",
        views.ajax_reorder_product_images,
        name="product-images-reorder",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/upload/$",
        views.ajax_upload_image,
        name="product-images-upload",
    ),
    url(r"attributes/$", views.attribute_list, name="attributes"),
    url(
        r"attributes/(?P<pk>[0-9]+)/$",
        views.attribute_details,
        name="attribute-details",
    ),
    url(r"attributes/add/$", views.attribute_create, name="attribute-add"),
    url(
        r"attributes/(?P<pk>[0-9]+)/update/$",
        views.attribute_edit,
        name="attribute-update",
    ),
    url(
        r"attributes/(?P<pk>[0-9]+)/delete/$",
        views.attribute_delete,
        name="attribute-delete",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/value/add/$",
        views.attribute_value_create,
        name="attribute-value-add",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/update/$",  # noqa
        views.attribute_value_edit,
        name="attribute-value-update",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/delete/$",  # noqa
        views.attribute_value_delete,
        name="attribute-value-delete",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/values/reorder/$",
        views.ajax_reorder_attribute_values,
        name="attribute-values-reorder",
    ),
]

saleor/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"^(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/$",
        views.product_details,
        name="details",
    ),
    url(
        r"^digital-download/(?P<token>[0-9A-Za-z_\-]+)/$",
        views.digital_product,
        name="digital-product",
    ),
    url(
        r"^category/(?P<slug>[a-z0-9-_]+?)-(?P<category_id>[0-9]+)/$",
        views.category_index,
        name="category",
    ),
    url(
        r"(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/add/$",
        views.product_add_to_checkout,
        name="add-to-checkout",
    ),
    url(
        r"^collection/(?P<slug>[a-z0-9-_/]+?)-(?P<pk>[0-9]+)/$",
        views.collection_index,
        name="collection",
    ),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r"^dashboard/", include((dashboard_urls, "dashboard"), namespace="dashboard")),
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/", include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(*translatable_urlpatterns)

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        """The debug toolbar was not installed. Ignore the error.
        settings.py should already have warned the user about it."""
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

    urlpatterns += [
        # static files (images, css, javascript, etc.)
        url(r"^static/(?P<path>.*)$", serve)
    ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

saleor/dashboard/product/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, reverse
from django.template.response import TemplateResponse
from django.utils.translation import npgettext_lazy, pgettext_lazy
from django.views.decorators.http import require_POST

from ...core.utils import get_paginator_items
from ...product.models import (
    Attribute,
    AttributeValue,
    Product,
    ProductImage,
    ProductType,
    ProductVariant,
)
from ...product.utils.availability import get_product_availability
from ...product.utils.costs import get_margin_for_variant, get_product_costs_data
from ...product.tasks import update_product_minimal_variant_price_task
from ..views import staff_member_required
from . import forms
from .filters import AttributeFilter, ProductFilter, ProductTypeFilter


@staff_member_required
@permission_required("product.manage_products")
def product_list(request):
    products = Product.objects.prefetch_related("images")
    products = products.order_by("name")
    product_types = ProductType.objects.all()
    product_filter = ProductFilter(request.GET, queryset=products)
    products = get_paginator_items(
        product_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "bulk_action_form": forms.ProductBulkUpdate(),
        "products": products,
        "product_types": product_types,
        "filter_set": product_filter,
        "is_empty": not product_filter.queryset.exists(),
    }
    return TemplateResponse(request, "dashboard/product/list.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def product_details(request, pk):
    products = Product.objects.prefetch_related("variants", "images").all()
    product = get_object_or_404(products, pk=pk)
    variants = product.variants.all()
    images = product.images.all()
    availability = get_product_availability(
        product,
        discounts=request.discounts,
        country=request.country,
        extensions=request.extensions,
    )
    sale_price = availability.price_range_undiscounted
    discounted_price = availability.price_range
    purchase_cost, margin = get_product_costs_data(product)

    # no_variants is True for product types that doesn't require variant.
    # In this case we're using the first variant under the hood to allow stock
    # management.
    no_variants = not product.product_type.has_variants
    only_variant = variants.first() if no_variants else None
    ctx = {
        "product": product,
        "sale_price": sale_price,
        "discounted_price": discounted_price,
        "variants": variants,
        "images": images,
        "no_variants": no_variants,
        "only_variant": only_variant,
        "purchase_cost": purchase_cost,
        "margin": margin,
        "is_empty": not variants.exists(),
    }
    return TemplateResponse(request, "dashboard/product/detail.html", ctx)


@require_POST
@staff_member_required
@permission_required("product.manage_products")
def product_toggle_is_published(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.is_published = not product.is_published
    product.save(update_fields=["is_published"])
    return JsonResponse({"success": True, "is_published": product.is_published})


@staff_member_required
@permission_required("product.manage_products")
def product_select_type(request):
    """View for add product modal embedded in the product list view."""
    form = forms.ProductTypeSelectorForm(request.POST or None)
    status = 200
    if form.is_valid():
        redirect_url = reverse(
            "dashboard:product-add",
            kwargs={"type_pk": form.cleaned_data.get("product_type").pk},
        )
        return (
            JsonResponse({"redirectUrl": redirect_url})
            if request.is_ajax()
            else redirect(redirect_url)
        )
    elif form.errors:
        status = 400
    ctx = {"form": form}
    template = "dashboard/product/modal/select_type.html"
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required("product.manage_products")
def product_create(request, type_pk):
    track_inventory = request.site.settings.track_inventory_by_default
    product_type = get_object_or_404(ProductType, pk=type_pk)
    create_variant = not product_type.has_variants
    product = Product()
    product.product_type = product_type
    product_form = forms.ProductForm(request.POST or None, instance=product)
    if create_variant:
        variant = ProductVariant(product=product, track_inventory=track_inventory)
        variant_form = forms.ProductVariantForm(
            request.POST or None, instance=variant, prefix="variant"
        )
        variant_errors = not variant_form.is_valid()
    else:
        variant_form = None
        variant_errors = False

    if product_form.is_valid() and not variant_errors:
        product = product_form.save()
        if create_variant:
            variant.product = product
            variant_form.save()
        msg = pgettext_lazy("Dashboard message", "Added product %s") % (product,)
        messages.success(request, msg)
        return redirect("dashboard:product-details", pk=product.pk)
    ctx = {
        "product_form": product_form,
        "variant_form": variant_form,
        "product": product,
    }
    return TemplateResponse(request, "dashboard/product/form.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def product_edit(request, pk):
    product = get_object_or_404(
        Product.objects.prefetch_related("variants", "product_type__attributeproduct"),
        pk=pk,
    )
    form = forms.ProductForm(request.POST or None, instance=product)
    edit_variant = not product.product_type.has_variants
    if edit_variant:
        variant = product.variants.first()
        variant_form = forms.ProductVariantForm(
            request.POST or None, instance=variant, prefix="variant"
        )
        variant_errors = not variant_form.is_valid()
    else:
        variant_form = None
        variant_errors = False

    if form.is_valid() and not variant_errors:
        product = form.save()
        if edit_variant:
            variant_form.save()
        msg = pgettext_lazy("Dashboard message", "Updated product %s") % (product,)
        messages.success(request, msg)
        return redirect("dashboard:product-details", pk=product.pk)
    ctx = {"product": product, "product_form": form, "variant_form": variant_form}
    return TemplateResponse(request, "dashboard/product/form.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        product.delete()
        msg = pgettext_lazy("Dashboard message", "Removed product %s") % (product,)
        messages.success(request, msg)
        return redirect("dashboard:product-list")
    return TemplateResponse(
        request, "dashboard/product/modal/confirm_delete.html", {"product": product}
    )


@require_POST
@staff_member_required
@permission_required("product.manage_products")
def product_bulk_update(request):
    form = forms.ProductBulkUpdate(request.POST)
    if form.is_valid():
        form.save()
        count = len(form.cleaned_data["products"])
        msg = npgettext_lazy(
            "Dashboard message",
            "%(count)d product has been updated",
            "%(count)d products have been updated",
            number="count",
        ) % {"count": count}
        messages.success(request, msg)
    return redirect("dashboard:product-list")


@staff_member_required
def ajax_products_list(request):
    """Return products filtered by request GET parameters.

    Response format is that of a Select2 JS widget.
    """
    queryset = (
        Product.objects.all()
        if request.user.has_perm("product.manage_products")
        else Product.objects.published()
    )
    search_query = request.GET.get("q", "")
    if search_query:
        queryset = queryset.filter(Q(name__icontains=search_query))
    products = [{"id": product.id, "text": str(product)} for product in queryset]
    return JsonResponse({"results": products})


@staff_member_required
@permission_required("product.manage_products")
def product_type_list(request):
    types = (
        ProductType.objects.all()
        .prefetch_related("product_attributes", "variant_attributes")
        .order_by("name")
    )
    type_filter = ProductTypeFilter(request.GET, queryset=types)
    types = get_paginator_items(
        type_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    types.object_list = [
        (pt.pk, pt.name, pt.product_attributes.all(), pt.variant_attributes.all())
        for pt in types.object_list
    ]
    ctx = {
        "product_types": types,
        "filter_set": type_filter,
        "is_empty": not type_filter.queryset.exists(),
    }
    return TemplateResponse(request, "dashboard/product/product_type/list.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def product_type_create(request):
    product_type = ProductType()
    form = forms.ProductTypeForm(request.POST or None, instance=product_type)
    if form.is_valid():
        product_type = form.save()
        msg = pgettext_lazy("Dashboard message", "Added product type %s") % (
            product_type,
        )
        messages.success(request, msg)
        return redirect("dashboard:product-type-list")
    ctx = {"form": form, "product_type": product_type}
    return TemplateResponse(request, "dashboard/product/product_type/form.html", ctx)


@staff_member_required
@permission_required("product.manage_products")

templates/dashboard/product/product_image/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}
  {% if product_image.pk %}
    {% trans "Edit - Image" context "Image form text" %}
  {% else %}
    {% trans "Add image" context "Image form text" %}
  {% endif %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-store body-products{% endblock %}

{% block menu_products_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:product-details" pk=product.pk as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:product-details" pk=product.pk %}" class="breadcrumbs--ellipsed-item">
        {{ product }}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:product-details" pk=product.pk %}" class="breadcrumb">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    {% if product_image.pk %}
      <li>
        <span class="breadcrumbs--ellipsed-item">
          {% trans "Image" context "Image form text" %}
        </span>
      </li>
      <li>
        <span class="breadcrumbs--ellipsed-item">
          {% trans "Edit" context "Image form text" %}
        </span>
      </li>
    {% else %}
      <li>
        <span class="hide-on-med-and-down">
          {% trans "Add image" context "Image form breadcrumbs" %}
        </span>
        <span class="hide-on-large-only breadcrumbs--ellipsed-item">
          {% blocktrans trimmed context "Image form breadcrumbs"  %}
            Add image for {{ product }}
          {% endblocktrans %}
        </span>
      </li>
    {% endif %}
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      <div class="card">
        <form method="post" enctype="multipart/form-data">
          <div class="card-content">
            {% csrf_token %}
            <div class="row">
              {{ form.image|materializecss }}
            </div>
            <div class="row">
              {{ form.alt|materializecss }}
            </div>
          </div>
          <div class="card-action right-align">
            <a href="{% url "dashboard:product-image-list" product.pk %}" class="btn-flat waves-effect">
              {% trans "Cancel" context "Dashboard cancel action" %}
            </a>
            {% if product_image.pk %}
              <button type="submit" class="btn waves-effect">
                {% trans "Save" context "Dashboard update action" %}
              </button>
            {% else %}
              <button type="submit" class="btn waves-effect">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col s12 m3 help-box"></div>
  </div>
{% endblock %}

templates/dashboard/product/product_image/list.html
{% extends "dashboard/base.html" %}

{% load i18n %}
{% load static %}

{% block title %}
  {% trans "Images" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-products{% endblock %}

{% block menu_products_class %}active{% endblock %}

{% block header_extra %}
  <div class="btn-fab-fixed">
    <a class="btn-fab-default waves-effect waves-light"
       id="images-btn"
       href="{% url 'dashboard:product-image-add' product_pk=product.pk %}"
       title="{% trans "Add image" context "Add image button text" %}">
      <svg data-src="{% static "dashboard/images/add.svg" %}" />
    </a>
  </div>
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:product-list" %}" class="breadcrumb">
        {% trans "Products" context "Dashboard products list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:product-list" %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <a href="{% url "dashboard:product-details" product.pk %}">{{ product }}</a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">{% trans "Images" %}</span>
    </li>
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div id="images" class="tab-content col s12 m9">
      <form action="{% url 'dashboard:product-images-upload' product_pk=product.pk %}" id="product-image-form" novalidate>
        <div class="dz-message"></div>
        {% csrf_token %}
        <div class="row">
          <ul class="product-gallery sortable-items" data-post-url="{% url 'dashboard:product-images-reorder' product_pk=product.pk %}" data-post-name="ordered_images">
            {% if images %}
              {% for image in images %}
                <li class="col s12 m6 l4 sortable-item"
                    data-id="{{ image.pk }}">
                  <div class="card">
                    <div class="card-image product-gallery-item-image">
                      <img class="responsive-img"
                           src="{{ image.image.thumbnail.255x255 }}"
                           srcset="{{ image.image.thumbnail.255x255 }} 1x, {{ image.image.thumbnail.510x510 }} 2x"
                           alt="">
                    </div>
                    <div class="card-content">
                      <span class="product-gallery-item-title card-title black-text" title="{{ image.alt }}">
                        {% if image.alt %}
                          {{ image.alt }}
                        {% else %}
                          <span class="grey-text">
                            {% trans "No description" context "Image card text" %}
                          </span>
                        {% endif %}
                      </span>
                    </div>
                    <div class="sortable__drag-area"></div>
                    <div class="card-action">
                      <a class="btn-flat waves-effect"
                         href="{% url 'dashboard:product-image-update' product_pk=product.pk img_pk=image.pk %}">
                        {% trans "Edit" context "Dashboard edit action" %}
                      </a>
                      <a href="#base-modal"
                         class="btn-flat waves-effect modal-trigger-custom"
                         data-href="{% url 'dashboard:product-image-delete' product_pk=product.pk img_pk=image.pk %}">
                        {% trans "Remove" context "Dashboard remove action" %}
                      </a>
                    </div>
                  </div>
                </li>
              {% endfor %}
            {% else %}
              <div class="sortable__drag-area"></div>
            {% endif %}
          </ul>
        <div class="col s12 m6 l4 product-gallery-item dropzone-message">
          <div class="row">
            <span class="product-gallery-item-title product-gallery-item-title--noclip card-title black-text">
              <span class="grey-text hide-on-med-and-down">
                {% trans "Drop images here to upload" context "Image gallery upload box text" %}
              </span>
            </span>
          </div>
        </div>
      </div>
      </form>
      <script type="application/template" id="template">
        <li class="col s12 m6 l4 product-gallery-item dz-preview dz-file-preview" data-id="{{ image.pk }}">
          <div class="card">
            <div class="card-image product-gallery-item-image">
              <img data-dz-thumbnail />
            </div>
            <div class="dz-progress">
              <span class="dz-upload" data-dz-uploadprogress></span>
            </div>
            <div class="card-content">
              <span class="product-gallery-item-title card-title black-text">
                <span class="grey-text">
                  {% trans "No description" context "Empty image gallery message" %}
                </span>
              </span>
            </div>
            <div class="sortable__drag-area"></div>
            <div class="card-action">
              <a class="btn-flat waves-effect card-action-edit" data-href-template="{% url 'dashboard:product-image-update' product_pk=product.pk img_pk=0 %}">
                {% trans "Edit" context "Dashboard edit action" %}
              </a>
              <a href="#base-modal" class="btn-flat waves-effect card-action-delete modal-trigger-custom"
              data-href-template="{% url 'dashboard:product-image-delete' product_pk=product.pk img_pk=0 %}">
                {% trans "Remove" context "Dashboard remove action" %}
              </a>
            </div>
            </div>
        </li>
      </script>
    </div>
  </div>
{% endblock %}

templates/dashboard/product/product_image/versatile_image.html
{% load i18n %}

{% if widget.is_initial %}
{% endif %}
<div class="sizedimage-mod preview">
  <label class="versatileimagefield-label">
    {% trans "Primary Point of Interest" %}
  </label>
  <p class="margin">
    {% trans "Pick the most relevant part of the image using the red circle." context "Image form text" %}
  </p>
  <div class="image-wrap outer">
    <div class="point-stage" id="{{ widget.point_stage_id }}" data-image_preview_id="{{ widget.image_preview_id }}">
      <div class="ppoi-point" id="{{ widget.ppoi_id }}"></div>
    </div>
    {% if widget.value %}
      <div class="image-wrap inner">
        <img src="{{ widget.sized_url }}" id="{{ widget.image_preview_id }}"
             data-hidden_field_id="{{ widget.hidden_field_id }}"
             data-point_stage_id="{{ widget.point_stage_id }}"
             data-ppoi_id="{{ widget.ppoi_id }}" class="sizedimage-preview"/>
      </div>
    {% endif %}
  </div>
</div>